server:
  port: 8085

spring:
  application:
    name: main-api-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/demoDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootuser
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  instance:
    instance-id: main-api-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka